INSERT INTO company (company_id, company_name)
VALUES
  (1, 'Abarth'),
  (2, 'Alpha Romeo'),
  (3, 'Aston Martin'),
  (4, 'Audi'),
  (5, 'Bentley'),
  (6, 'BMW'),
  (7, 'Cadillac'),
  (8, 'Chevrolet'),
  (9, 'Chrysler'),
  (10, 'Citroën'),
  (11, 'Dacia'),
  (12, 'Daewoo'),
  (13, 'Daihatsu'),
  (14, 'Dodge'),
  (15, 'DS'),
  (16, 'Ferrari'),
  (17, 'Fiat'),
  (18, 'Ford'),
  (19, 'Great Wall'),
  (20, 'Honda'),
  (21, 'Hyundai'),
  (22, 'Infiniti'),
  (23, 'Isuzu'),
  (24, 'Iveco'),
  (25, 'Jaguar'),
  (26, 'Jeep'),
  (27, 'Kia'),
  (28, 'Lancia'),
  (29, 'Land Rover'),
  (30, 'Lexus'),
  (31, 'MAN'),
  (32, 'Maserati'),
  (33, 'Maxus'),
  (34, 'Mazda'),
  (35, 'Mercedes'),
  (36, 'MG'),
  (37, 'Mini'),
  (38, 'Mitsubishi'),
  (39, 'Nissan'),
  (40, 'Opel'),
  (41, 'Peugeot'),
  (42, 'Porsche'),
  (43, 'Renault'),
  (44, 'Seat'),
  (45, 'Škoda'),
  (46, 'Smart'),
  (47, 'SsangYong'),
  (48, 'Subaru'),
  (49, 'Suzuki'),
  (50, 'Toyota'),
  (51, 'Volkswagen'),
  (52, 'Volvo'),
  (53, 'אחר');